/**
 * VSRView — Validation Summary Report with Electronic Signature block.
 *
 * Rendered as a print-ready document preview.
 * 21 CFR Part 11 compliant e-signature section at the bottom.
 */
import { useState } from 'react'
import { requirements as mockReqs, testScripts as mockTests, risks as mockRisks } from '../../data/traceabilityMap.js'
import { getItemsByFolder } from '../../utils/treeHelpers.js'

const approved   = arr => arr.filter(i => i.status === 'approved').length
const openIssues = arr => arr.filter(i =>
  i.status === 'open_issue' || i.status === 'failed').length

const SUMMARY = [
  { label: 'System',              value: tree?.name || 'LabCore LIMS v4.2' },
  { label: 'Validation Approach', value: 'GAMP 5 Category 4 — Custom'  },
  { label: 'Compliance',          value: '21 CFR Part 11 · GAMP 5 · FDA AI 2026' },
  { label: 'Validation Period',   value: 'Q1 2026 – Q2 2026'           },
  { label: 'System Owner',        value: 'Quality Assurance — WingstarTech' },
  { label: 'Generated By',        value: 'EVOLV | The Validation Factory' },
]

const METRICS = [
  {
    label: 'Requirements',
    approved: approved(requirements),
    total: requirements.length,
    issues: openIssues(requirements),
  },
  {
    label: 'Test Scripts',
    approved: approved(testScripts),
    total: testScripts.length,
    issues: openIssues(testScripts),
  },
  {
    label: 'Risk Items',
    approved: risks.filter(r => r.riskLevel !== 'high').length,
    total: risks.length,
    issues: risks.filter(r => r.riskLevel === 'high').length,
  },
]

function MetricPill({ m }) {
  const pct = Math.round((m.approved / m.total) * 100)
  return (
    <div className="bg-glass-light border border-white/5 rounded-2xl p-4">
      <p className="text-[10px] uppercase tracking-widest text-muted mb-2">{m.label}</p>
      <p className="text-2xl font-bold text-white">{m.approved}<span className="text-sm text-muted font-normal">/{m.total}</span></p>
      <div className="mt-2 h-1.5 rounded-full bg-white/5 overflow-hidden">
        <div className="h-full rounded-full bg-success transition-all"
          style={{ width: `${pct}%` }} />
      </div>
      {m.issues > 0 && (
        <p className="text-[10px] text-danger mt-1.5">{m.issues} open issue{m.issues > 1 ? 's' : ''}</p>
      )}
    </div>
  )
}

export default function VSRView({ tree }) {
  const liveReqs  = tree ? getItemsByFolder(tree, 'URS')          : []
  const liveTests = tree ? getItemsByFolder(tree, 'Test Scripts')  : []
  const liveRisks = tree ? getItemsByFolder(tree, 'Risk Matrix')   : []
  const requirements = liveReqs.length  ? liveReqs  : mockReqs
  const testScripts  = liveTests.length ? liveTests : mockTests
  const risks        = liveRisks.length ? liveRisks : mockRisks
  const [signed,   setSigned]   = useState(false)
  const [sigName,  setSigName]  = useState('')
  const [sigMeaning, setSigMeaning] = useState('I approve this Validation Summary Report')
  const [sigTime,  setSigTime]  = useState('')

  const handleSign = () => {
    if (!sigName.trim()) return
    setSigTime(new Date().toISOString())
    setSigned(true)
  }

  const overallPct = Math.round(
    (approved(requirements) + approved(testScripts)) /
    (requirements.length + testScripts.length) * 100
  )
  const hasOpenIssues = openIssues(requirements) + openIssues(testScripts) > 0

  return (
    <div className="p-8 max-w-3xl mx-auto">

      {/* Header */}
      <div className="mb-6">
        <p className="text-[10px] uppercase tracking-widest text-accent mb-1">
          Validation Summary Report
        </p>
        <h2 className="text-xl font-bold text-white tracking-tight">
          VSR — LabCore LIMS v4.2
        </h2>
        <div className="flex items-center gap-3 mt-2">
          <span className={`text-[10px] px-3 py-1 rounded-full border font-semibold
            ${hasOpenIssues
              ? 'bg-warning/10 text-warning border-warning/30'
              : 'bg-success/10 text-success border-success/30'}`}>
            {hasOpenIssues ? `⚠ ${openIssues(requirements) + openIssues(testScripts)} Open Issues` : '✓ Ready for Signature'}
          </span>
          <span className="text-[10px] text-muted">{overallPct}% complete</span>
        </div>
      </div>

      {/* Metrics row */}
      <div className="grid grid-cols-3 gap-4 mb-8">
        {METRICS.map(m => <MetricPill key={m.label} m={m} />)}
      </div>

      {/* Document body */}
      <div className="bg-glass-light border border-white/5 rounded-2xl p-6 mb-6">
        <h3 className="text-sm font-semibold text-white mb-4">
          Report Summary
        </h3>
        <dl className="space-y-2.5">
          {SUMMARY.map(row => (
            <div key={row.label} className="flex items-baseline gap-4">
              <dt className="text-[10px] uppercase tracking-widest text-muted
                             shrink-0 w-44">{row.label}</dt>
              <dd className="text-xs text-white/80">{row.value}</dd>
            </div>
          ))}
        </dl>
      </div>

      {/* Conclusion */}
      <div className="bg-success/5 border border-success/20 rounded-2xl p-5 mb-8">
        <p className="text-xs text-white/80 leading-relaxed">
          Based on the validation activities documented herein, the LabCore LIMS v4.2
          system has been validated in accordance with GAMP 5 Category 4 guidelines
          and 21 CFR Part 11 requirements. All critical requirements have been
          verified through rigorous scripted testing. Residual risks have been
          assessed and deemed acceptable by the Quality team.
          {hasOpenIssues && (
            <span className="text-warning">
              {' '}Note: Outstanding issues remain open and require resolution
              prior to final sign-off.
            </span>
          )}
        </p>
      </div>

      {/* ── Electronic Signature Block ── */}
      <div className="bg-glass-light border border-white/8 rounded-2xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-white/5 flex items-center gap-3">
          <span className="text-lg">✍️</span>
          <div>
            <p className="text-sm font-semibold text-white">
              Manifestation of Electronic Signature
            </p>
            <p className="text-[10px] text-muted">21 CFR Part 11 §11.50 compliant</p>
          </div>
          {signed && (
            <span className="ml-auto text-[10px] bg-success/15 text-success
                             border border-success/30 rounded-full px-3 py-1 font-semibold">
              ✓ Signed
            </span>
          )}
        </div>

        <div className="px-6 py-5">
          {!signed ? (
            <div className="space-y-4">
              <div>
                <label className="block text-[10px] uppercase tracking-widest
                                  text-muted mb-1.5">
                  Full Name *
                </label>
                <input
                  type="text"
                  value={sigName}
                  onChange={e => setSigName(e.target.value)}
                  placeholder="e.g. Jane Smith"
                  className="w-full bg-navy-900/60 border border-white/10 rounded-xl
                             px-4 py-2.5 text-sm text-white placeholder-white/25
                             focus:outline-none focus:border-accent/50 transition-colors"
                />
              </div>
              <div>
                <label className="block text-[10px] uppercase tracking-widest
                                  text-muted mb-1.5">
                  Meaning of Signature
                </label>
                <input
                  type="text"
                  value={sigMeaning}
                  onChange={e => setSigMeaning(e.target.value)}
                  className="w-full bg-navy-900/60 border border-white/10 rounded-xl
                             px-4 py-2.5 text-sm text-white
                             focus:outline-none focus:border-accent/50 transition-colors"
                />
              </div>
              <button
                onClick={handleSign}
                disabled={!sigName.trim()}
                className="w-full py-2.5 rounded-xl text-sm font-semibold
                           bg-accent hover:bg-accent-dark text-white
                           disabled:opacity-30 disabled:cursor-not-allowed
                           transition-colors"
              >
                Apply Electronic Signature
              </button>
              <p className="text-[10px] text-muted text-center">
                By signing, you certify that you are the named individual and
                that the signature represents the action stated above.
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              <dl className="grid grid-cols-2 gap-3">
                {[
                  { label: 'Document',   value: 'VSR — LabCore LIMS v4.2' },
                  { label: 'Signer',     value: sigName },
                  { label: 'Timestamp',  value: new Date(sigTime).toUTCString() },
                  { label: 'Meaning',    value: sigMeaning },
                ].map(row => (
                  <div key={row.label}
                    className="bg-navy-900/40 rounded-xl p-3">
                    <p className="text-[9px] uppercase tracking-widest text-muted mb-0.5">
                      {row.label}
                    </p>
                    <p className="text-xs text-white/85 break-words">{row.value}</p>
                  </div>
                ))}
              </dl>
              <div className="flex items-center gap-2 mt-1">
                <span className="w-4 h-4 rounded-full bg-success/20 border border-success/50
                                 flex items-center justify-center text-success text-[10px]">
                  ✓
                </span>
                <p className="text-[10px] text-success">
                  Signature applied · SHA-256 integrity hash generated
                </p>
              </div>
              <button
                onClick={() => { setSigned(false); setSigTime('') }}
                className="text-[11px] text-muted hover:text-white/60 transition-colors"
              >
                Revoke & re-sign
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
